server:
  port: 8080

spring:
  application:
    name: client-backend
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: rabbit
  security:
    user:
      name: ylica
      password: AbR@c4DaBr@3091.3
  rabbitmq:
    host: localhost
    port: 5672
    username: ylica
    password: P@ssw0rd
  datasource:
    url: jdbc:postgresql://localhost:5432/clients-backend
    username: ylica
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus

sonar:
  projectKey: client-backend
  projectName: client-backend
  host:
    url: http://localhost:9000
  login: 4795a6a184e252ed0f9dfe35c5e919a3145c959e