server:
  port: 8080

spring:
  application:
    name: client-backend
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        id:
          new_generator_mappings: false

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
